from resources.queries.skills import skills_info
from resources.queries.login import check_user_login
from resources.queries.registration_add_user import registration
from resources.queries.tasks import get_user_tasks
from resources.queries.team_info import team_list
from resources.queries.create_task import task_crt
from resources.queries.organization_name import get_organization_name
from resources.queries.leaderboard import get_leaderboard
from resources.queries.leaderboard_place import get_leaderboard_place
from resources.queries.update_task import task_status_upd
